### ISSUE TITLE
移动后导致Vsstudio2019定向不到解决方案

### ISSUE THREAD

**Issue by chers42** [memory-yiyi/MoveWinKits#1]
我的版本
Microsoft Windows [版本 10.0.19044.1706]
Vs2019+Vs2013

1.如果直接以管理员权限打开Start.bat会进行闪退
在尝试过这个后
我开始以WIN+R 输入cmd 再cd到目录开始执行
![image](https://user-images.githubusercontent.com/96336932/187854618-33214ae9-7986-464b-8c83-4f68fcfe6d49.png)

```
Source Path: I:\
Destination Path: E:\
Extract and import the key registry, and move the "Windows Kits" folder, please wait...
Move failed, please operate manually.
错误: 访问注册表时出错。
```
这个是我在执行如上操作的时候的报错信息

**Comment by chers42** [comment]
![image](https://user-images.githubusercontent.com/96336932/187854836-30e27646-0bf3-4fb2-88d4-ad23a6cfe42f.png)
尝试win+q 输入cmd 再右键打开管理员运行的结果E盘里面还是没有Windows kit

**Comment by chers42** [comment]
正在按照提示手动移动，发现我个人的window kit有10g

**Comment by chers42** [comment]
意外的发现，当window kits文件夹太大的时候程序会移动失败，这时候只需要手动移动到被你指定的文件夹下就行

**Comment by memory-yiyi** [comment]
对于因为文件夹过大自动移动失败的问题，如果拥有较多反馈，将进行改进，目前请手动移动文件夹，感谢你的反馈。

**Comment by memory-yiyi** [comment]
注册表注入错误，win+r进入cmd时没有管理员权限，无法合并注册表，这是你无法使用vs的原因之一，也可能是无法移动的原因，请重新运行程序，若还有问题，请继续反馈。

**Comment by memory-yiyi** [comment]
关于以管理员权限运行会闪退的问题，请检查你的电脑，或者提供更多的信息。
