### ISSUE TITLE
vs2022 执行项目无法找到windows SDk

### ISSUE THREAD

**Issue by xiaoye-2018** [memory-yiyi/MoveWinKits#2]
使用该项目移动windows SDK 目录后，使用vs 创建项目无法构建，一直提示无法找打Windows SDK
![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/83bb694a-5f7d-4ca3-8348-03536a9637eb)
SDK 目录如下：
![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/69d40538-5c43-4fd6-aee9-8f663152dcac)

**Comment by memory-yiyi** [comment]
您好，经过测试，对于多运行库是没有问题的，目前推测由以下问题导致：

- 未使用管理员身份运行导致一些注册表未获取或导入
- 手动移动文件夹位置导致不匹配（您可以检查一下日志注册表文件中标出的位置与库文件位置是否一致）

您可以尝试重新安装库文件，并再次运行脚本，如果还是无法使用，请给出以下信息：

1. 原库路径
2. 运行脚本版本
3. 运行信息（运行完毕后截图，以确定过程无报错）
4. 日志注册表文件（ChangeLogxxx.reg）
5. 移动位置截图
6. vs报错截图

以帮助开发人员发现并解决问题。

**Comment by xiaoye-2018** [comment]
上午已尝试重新安装了SDK 10.0.20348.0， 不想卸载vs 全部重试。
1. 原库路径： 几周前使用的该项目，目录记得是C：xxx，  这个应该是默认的吧
2. 脚本版本：2.1
3. 当初没有报错信息
4. 已手动改名，默认无法上传
[ChangeLog231128094137.reg.txt](https://github.com/memory-yiyi/MoveWinKits/files/13691700/ChangeLog231128094137.reg.txt)

5. 移动位置：
![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/e326c982-7583-48fe-8226-326b94445948)
6. vs：
![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/b3a5857c-5664-4714-a331-c04fd52319e6)

![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/af0e1acd-4c9a-4553-9069-f8a0bde8002b)


是否需要完全卸载vs 后，重新安装

**Comment by xiaoye-2018** [comment]
已经尝试重新安装整个程序，现在无法找到下载的sdk目录，windows kits 文件夹放哪里了

**Comment by memory-yiyi** [comment]
很抱歉，我无法复现您的问题。

按照默认安装，库的原始路径为`C:\Program Files (x86)\Windows Kits`，脚本2.1处理后，能正常运行，无报错。

请尝试导入日志注册表文件（ChangeLogxxx.reg），观察vs2022是否能找到库文件，如果还是无法找到，请重新安装vs2022，并再次尝试。

**Comment by xiaoye-2018** [comment]
已经重新安装vs 2022， 并多次重新安装sdk 其他版本后，在以前自定义的目录找到sdk，发现vs 中include 路径是这样的，是否是由于这里没有自定义前缀导致
![image](https://github.com/memory-yiyi/MoveWinKits/assets/46118372/22b3b913-525b-4afe-b649-2f54e89dc3b6)

**Comment by memory-yiyi** [comment]
那个是计算得到的值，说明你的配置出现了问题，正常来说那里应该写的是库文件的绝对路径，可能哪个环节出现了崩坏，但我无法复现您的状态。

**Comment by xiaoye-2018** [comment]
卸载软件是不是不会将之前注册表的配置全部清空？

**Comment by memory-yiyi** [comment]
您可以在卸载后使用`CCleaner`扫描无用注册表并修复然后重新安装，以保证vs2022能够顺利重新安装

**Comment by xiaoye-2018** [comment]
vs 2022 重装了几次无法解决，换成2017 可以了

**Comment by memory-yiyi** [comment]
由于无法复现您的问题，所以将关闭该会话，如果您还有其它问题可以新建或重启该会话。
